### ISSUE TITLE
Server Create

### ISSUE THREAD

**Issue by DomiHrajeCZ-Developer** [stanjg/Ptero4J#17]
Hello, how to create server? I have code, but code dont working:

			try {
				Main.api.getServersController()
				.createNew()
				.setName(serverowner)
				.setDescription("Owner: " + serverowner)
				.setUserId(9)
				.setEggId(3)
				.setAllocation(1)
				.setPackId(1)
				.setDockerImage("quay.io/pterodactyl/core:java")
				.setLimits(512, 0, 3000, 0, 100)
				.setFeatureLimits(0, 0)
				.setDedicatedIp(true)
				.setPortRange(portRange)
				.setStartOnCompletion(true)
				.setFeatureLimits(0, 0)
				.setDeployLocations(ids)
				.setSkipScripts(false)
				.setExternalId(503)
				.execute();
			} catch(Exception e) {
				e.printStackTrace();
			}

why?

error:
An error occurred while making a request to the panel, if the issue persists please create an issue on github.
422 POST https://panel.gamerhost.pro/api/application/servers

**Comment by DDarkInferno** [comment]
Got the same issue.

**Comment by TheAimWolf** [comment]
Hello,
I've got the same issue.
Code:
`ServersController controller = new ServersController(adminApi, HOST, ADMINKEY);
    	controller.createNew()
		.setExternalId(1234566)
		.setName("Minecraft Test")
		.setUserId(1)
		.setDescription("Hallo Welt")
		.setEggId(5)
		.setPackId(0)
		.setDockerImage("quay.io/pterodactyl/core:java")
		.setStartupCommand("java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}")
		.setLimits(4096, 2048, 5000, 100, 100)
		.setFeatureLimits(1, 2)
		.setAllocation(1)
		.setDeployLocations(1)
		.setDedicatedIp(false)
		.setPortRange("")
		.setStartOnCompletion(true)
		.setSkipScripts(false)
		.execute();`

I should provide this line:
`422 POST https://control.junico.de/api/application/servers`

Would be really nice if you could help us ;)

**Comment by DDarkInferno** [comment]
> Hello,
> I've got the same issue.
> Code:
> `ServersController controller = new ServersController(adminApi, HOST, ADMINKEY); controller.createNew() .setExternalId(1234566) .setName("Minecraft Test") .setUserId(1) .setDescription("Hallo Welt") .setEggId(5) .setPackId(0) .setDockerImage("quay.io/pterodactyl/core:java") .setStartupCommand("java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}") .setLimits(4096, 2048, 5000, 100, 100) .setFeatureLimits(1, 2) .setAllocation(1) .setDeployLocations(1) .setDedicatedIp(false) .setPortRange("") .setStartOnCompletion(true) .setSkipScripts(false) .execute();`
> 
> I should provide this line:
> `422 POST https://control.junico.de/api/application/servers`
> 
> Would be really nice if you could help us ;)

I fixed the issue by making a fork of the repository and editing it to my needs.

**Comment by TheAimWolf** [comment]
> > Hello,
> > I've got the same issue.
> > Code:
> > `ServersController controller = new ServersController(adminApi, HOST, ADMINKEY); controller.createNew() .setExternalId(1234566) .setName("Minecraft Test") .setUserId(1) .setDescription("Hallo Welt") .setEggId(5) .setPackId(0) .setDockerImage("quay.io/pterodactyl/core:java") .setStartupCommand("java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}") .setLimits(4096, 2048, 5000, 100, 100) .setFeatureLimits(1, 2) .setAllocation(1) .setDeployLocations(1) .setDedicatedIp(false) .setPortRange("") .setStartOnCompletion(true) .setSkipScripts(false) .execute();`
> > I should provide this line:
> > `422 POST https://control.junico.de/api/application/servers`
> > Would be really nice if you could help us ;)
> 
> I fixed the issue by making a fork of the repository and editing it to my needs.

@DDarkInferno 
May you help me out with this. What did you have to change? What was the issue with the original repository? Maybe you can post some lines that you had to change?

**Comment by DDarkInferno** [comment]
> > > Hello,
> > > I've got the same issue.
> > > Code:
> > > `ServersController controller = new ServersController(adminApi, HOST, ADMINKEY); controller.createNew() .setExternalId(1234566) .setName("Minecraft Test") .setUserId(1) .setDescription("Hallo Welt") .setEggId(5) .setPackId(0) .setDockerImage("quay.io/pterodactyl/core:java") .setStartupCommand("java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}") .setLimits(4096, 2048, 5000, 100, 100) .setFeatureLimits(1, 2) .setAllocation(1) .setDeployLocations(1) .setDedicatedIp(false) .setPortRange("") .setStartOnCompletion(true) .setSkipScripts(false) .execute();`
> > > I should provide this line:
> > > `422 POST https://control.junico.de/api/application/servers`
> > > Would be really nice if you could help us ;)
> > 
> > 
> > I fixed the issue by making a fork of the repository and editing it to my needs.
> 
> @DDarkInferno
> May you help me out with this. What did you have to change? What was the issue with the original repository? Maybe you can post some lines that you had to change?

https://github.com/DDarkInferno/Ptero4J

Then for your example, a Vanilla Minecraft Server, you could do something like 
.addEnvironmentValue(new CreationEnvironment("SERVER_JARFILE", "server.jar"))

You can find the necessary environment values here https://imgur.com/EV5LYLA, at the egg variables.

At least that's what I did to fix the error for me.

**Comment by TheAimWolf** [comment]
> > > > Hello,
> > > > I've got the same issue.
> > > > Code:
> > > > `ServersController controller = new ServersController(adminApi, HOST, ADMINKEY); controller.createNew() .setExternalId(1234566) .setName("Minecraft Test") .setUserId(1) .setDescription("Hallo Welt") .setEggId(5) .setPackId(0) .setDockerImage("quay.io/pterodactyl/core:java") .setStartupCommand("java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}") .setLimits(4096, 2048, 5000, 100, 100) .setFeatureLimits(1, 2) .setAllocation(1) .setDeployLocations(1) .setDedicatedIp(false) .setPortRange("") .setStartOnCompletion(true) .setSkipScripts(false) .execute();`
> > > > I should provide this line:
> > > > `422 POST https://control.junico.de/api/application/servers`
> > > > Would be really nice if you could help us ;)
> > > 
> > > 
> > > I fixed the issue by making a fork of the repository and editing it to my needs.
> > 
> > 
> > @DDarkInferno
> > May you help me out with this. What did you have to change? What was the issue with the original repository? Maybe you can post some lines that you had to change?
> 
> https://github.com/DDarkInferno/Ptero4J
> 
> Then for your example, a Vanilla Minecraft Server, you could do something like
> .addEnvironmentValue(new CreationEnvironment("SERVER_JARFILE", "server.jar"))
> 
> You can find the necessary environment values here https://imgur.com/EV5LYLA, at the egg variables.
> 
> At least that's what I did to fix the error for me.

Hmm, this doesn't work too. I tried it with diffrent types of servers with the envoirmental variables, but the error remains the same:
`controller.createNew()
		.addEnvironmentValue(new CreationEnvironment("TS_VERSION", "latest"))
		.addEnvironmentValue(new CreationEnvironment("FILE_TRANSFER", "30033"))
		.setName("TS SERVER1")
		.setUserId(1)
		.setDescription("Hallo Welt")
		.setEggId(13)
		.setDockerImage("quay.io/parkervcp/pterodactyl-images:base_debian")
		.setStartupCommand("./ts3server default_voice_port={{SERVER_PORT}} query_port={{SERVER_PORT}} filetransfer_ip=0.0.0.0 filetransfer_port={{FILE_TRANSFER}} license_accepted=1")
		.setLimits(4096, 2048, 5000, 100, 100)
		.setFeatureLimits(1, 2)
		.setAllocation(9987)
		.setDeployLocations(1)
		.setDedicatedIp(false)
		.setPortRange("")
		.setStartOnCompletion(true)
		.setSkipScripts(false)
		.execute();`
In this example I tried to add an Teamspeak server. Have I understood anything wrong?

**Comment by stijnb1234** [comment]
Same issue here.

**Comment by sdfaken** [comment]
I'm still looking for a fix, @DDarkInferno's solution did not help me. I still get the same error.

**Comment by JacobPassam** [comment]
+1 same issue

**Comment by stijnb1234** [comment]
I recommend using https://github.com/mattmalec/Pterodactyl4J temporarily, until it's fixed.
